# Generated by Django 4.2.7 on 2024-01-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_patient_dossier_medical'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier_medical',
            old_name='pastien',
            new_name='patien',
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('heur', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
    ]
