# Generated by Django 4.2.7 on 2024-01-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_category_commande_ingredient_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dprt', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Dossier_Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Traitement_medical', models.CharField(max_length=1000)),
                ('prescriptions', models.CharField(max_length=50)),
                ('Dpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_med', models.CharField(max_length=50)),
                ('prenom_med', models.CharField(max_length=50)),
                ('specialite', models.CharField(max_length=50)),
                ('num_tel_med', models.FloatField(max_length=10)),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_patient', models.CharField(max_length=50)),
                ('prenom_patient', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=50)),
                ('num_tel', models.FloatField(max_length=10)),
                ('date_naissance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('heur', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='dossier_medical',
            name='patien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient'),
        ),
    ]
