# Generated by Django 4.2.7 on 2024-01-20 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_medecin_num_tel_med_remove_patient_num_tel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='heur',
            new_name='heure',
        ),
    ]
