# Generated by Django 4.2.7 on 2024-01-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_heur_rdv_heure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dossier_medical',
            old_name='patien',
            new_name='patient',
        ),
    ]
