# Generated by Django 4.2.7 on 2024-01-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_rename_patien_dossier_medical_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Adr',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
