# Generated by Django 4.2.7 on 2024-01-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_patient_num_tel_patient_alter_patient_nss'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='num_tel_med',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
