# Generated by Django 5.0.2 on 2024-02-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_medecin_num_tel_med'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chall_num', models.IntegerField()),
                ('chall_name', models.CharField(max_length=50)),
                ('chall_desc', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Critics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_name', models.CharField(max_length=50)),
                ('cri_desc', models.CharField(max_length=2000)),
                ('coef', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jfirst_name', models.CharField(max_length=50)),
                ('Jlast_name', models.CharField(max_length=50)),
                ('Jtitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='Departement',
        ),
        migrations.RemoveField(
            model_name='dossier_medical',
            name='Dpt',
        ),
        migrations.RemoveField(
            model_name='dossier_medical',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='Medecin',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='Patient',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rev_note', models.IntegerField()),
                ('Challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.challenge')),
                ('Judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('repo_link', models.CharField(max_length=1000)),
                ('design_link', models.CharField(max_length=1000)),
                ('presentation_link', models.CharField(max_length=1000)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.challenge')),
            ],
        ),
        migrations.DeleteModel(
            name='Departement',
        ),
        migrations.DeleteModel(
            name='Dossier_Medical',
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='RDV',
        ),
    ]
