# Generated by Django 4.2.7 on 2024-01-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_medecin_num_tel_med_patient_num_tel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='num_tel_med',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='num_tel',
        ),
    ]
