# Generated by Django 4.2.7 on 2024-01-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_patient_adr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Adr',
            new_name='NSS',
        ),
    ]
