# Generated by Django 4.2.7 on 2024-01-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_rename_adr_patient_nss'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='num_tel_patient',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='NSS',
            field=models.IntegerField(),
        ),
    ]
