# Generated by Django 5.0.2 on 2024-02-09 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_challenge_critics_judge_remove_medecin_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Critic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri_name', models.CharField(max_length=50)),
                ('cri_desc', models.CharField(max_length=2000)),
                ('cri_coef', models.IntegerField()),
                ('cri_chall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.challenge')),
                ('cri_judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.judge')),
            ],
        ),
        migrations.DeleteModel(
            name='Critics',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
