# Generated by Django 4.2.7 on 2024-01-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_medecin_num_tel_med_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medecin',
            name='num_tel_med',
            field=models.FloatField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='num_tel',
            field=models.FloatField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
